name: klubnikakg1
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  bloc: ^8.0.3
  scoped_model: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  table_calendar: ^3.0.6
  flutter_svg: ^1.1.1+1
  flutter_localizations:

    sdk: flutter
  intl: ^0.17.0


dev_dependencies:
  bloc_test: ^9.0.3
  dartz: ^0.10.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  table_calendar: ^3.0.7
  very_good_analysis: ^3.0.1
  syncfusion_flutter_calendar: ^20.3.50

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icon/
